services:
  server-health-go:
    build: .
    container_name: server-health-go
    ports:
      - "8080:8080"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
