# prometheus.yaml

global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'server-health-go'
    scrape_interval: 15s
    static_configs:
      - targets: ['server-health-go:8080']
